services:
  - type: web
    name: accommodation  # Your project name as the service name
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn accommodation.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: accommodation.settings.production  # Use your production settings
    routes:
      - src: /static/*
        dest: /static/
      - src: /media/*
        dest: /media/
