services:
  - type: web
    name: accommodation
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      gunicorn accommodation.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: accommodation.settings.production
    disk:
      name: media-disk
      mountPath: /data/media/
staticPublish:
  - name: static-files
    source: /staticfiles
    destination: /static
  - name: media-files
    source: /data/media/
    destination: /media/
