services:
  - type: web
    name: accommodation
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      cp nginx.conf /etc/nginx/nginx.conf  # Ensure the nginx.conf is copied correctly
    startCommand: |
      service nginx start && gunicorn accommodation.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: accommodation.settings.production
    routes:
      - src: /static/*
        dest: /static/
      - src: /media/*
        dest: /media/
