services:
  - type: web
    name: accommodation
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      apt-get update && apt-get install -y nginx  # Install Nginx
      service nginx start                        # Start Nginx
      gunicorn accommodation.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: accommodation.settings.production
    routes:
      - src: /static/*
        dest: /static/
      - src: /media/*
        dest: /media/
