services:
  - type: web
    name: accommodation  # Use the actual project/service name
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      cp nginx.conf /etc/nginx/nginx.conf  # Copy custom NGINX config
    startCommand: |
      service nginx start && gunicorn accommodation.wsgi:application --bind 0.0.0.0:8000
    routes:
      - src: /*
        dest: /
