# Generated by Django 5.1 on 2024-08-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="hostel",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
