# Generated by Django 5.1 on 2024-08-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentauth", "0002_studentprofile_hostel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="hostel",
            field=models.CharField(
                blank=True,
                choices=[("white house", "WHITE HOUSE"), ("jabi", "JABI")],
                max_length=200,
                null=True,
            ),
        ),
    ]
