# Generated by Django 5.1 on 2024-08-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentauth", "0003_alter_studentprofile_hostel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
