# Generated by Django 5.1 on 2024-09-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentauth", "0006_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
