# Generated by Django 5.0.6 on 2024-09-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentauth", "0007_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
