# Generated by Django 5.0.6 on 2024-09-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentauth", "0008_studentprofile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="student_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
