# Generated by Django 5.0.6 on 2024-09-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentauth", "0009_studentprofile_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=20,
                null=True,
            ),
        ),
    ]
