# Generated by Django 5.0.6 on 2024-09-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentauth", "0010_alter_customuser_gender_alter_studentprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="school",
            field=models.CharField(
                blank=True,
                choices=[("nile", "Nile"), ("baze", "Baze")],
                max_length=20,
                null=True,
            ),
        ),
    ]
