# Generated by Django 5.0.6 on 2024-09-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentauth", "0011_customuser_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="kin_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="kin_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="level",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="next_of_kin_fullname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
