# Generated by Django 5.1 on 2024-10-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentauth", "0012_customuser_kin_address_customuser_kin_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="student_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
