# Generated by Django 5.1 on 2024-10-22 08:54

import studentauth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studentauth", "0013_alter_customuser_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="image",
            field=models.FileField(
                blank=True,
                default="default.jpg",
                null=True,
                upload_to=studentauth.models.user_directory_path,
            ),
        ),
    ]
