# Generated by Django 5.0.6 on 2024-09-03 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="hostel",
            table="hostel_hostel",
        ),
    ]
