# Generated by Django 5.1 on 2024-12-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0002_bedspace_room_booking_room_maintenance_request_room_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostel",
            name="image",
            field=models.FileField(upload_to="hostel_gallery/"),
        ),
    ]
