# Generated by Django 5.1 on 2024-12-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0003_alter_hostel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostel",
            name="image",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
