# Generated by Django 5.0.6 on 2024-09-05 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0003_alter_hostel_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hostel",
            name="user",
        ),
    ]
