# Generated by Django 5.1 on 2024-12-08 23:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0004_alter_hostel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostel",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
