# Generated by Django 5.0.6 on 2024-09-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0005_hostel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="active",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Draft", "Draft"),
                    ("Disabled", "Disabled"),
                    ("Not Available", "Not Available"),
                    ("Active", "Active"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
