# Generated by Django 5.0.6 on 2024-09-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0006_hostel_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostel",
            name="active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
