# Generated by Django 5.0.6 on 2024-09-06 13:27

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0007_alter_hostel_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="current_occupancy",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("student_id", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "check_in_tracker",
                    models.BooleanField(
                        default=False,
                        help_text="CHECK THIS BOX ONLY WHEN STUDENT CHECKS IN",
                    ),
                ),
                (
                    "check_out_tracker",
                    models.BooleanField(
                        default=False,
                        help_text="CHECK THIS BOX ONLY WHEN STUDENT CHECKS OUT",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "stripe_payment",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Processing", "Processing"),
                            ("Paid", "Paid"),
                            ("Declined", "Declined"),
                            ("In-review", "In-review"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "success_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
                        length=10,
                        max_length=505,
                        prefix="",
                    ),
                ),
                (
                    "booking_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
                        length=10,
                        max_length=20,
                        prefix="",
                        unique=True,
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hostel.hostel"
                    ),
                ),
                (
                    "hostel_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hostel.hosteltype",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hostel.room"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
