# Generated by Django 5.0.6 on 2024-09-07 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0008_room_capacity_room_current_occupancy_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="BedSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bed_type",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=20,
                    ),
                ),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beds",
                        to="hostel.room",
                    ),
                ),
            ],
        ),
    ]
