# Generated by Django 5.0.6 on 2024-09-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0010_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="bed",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="bedspace",
            name="bed_type",
            field=models.CharField(choices=[("A,B,C", "A,B,C")], max_length=20),
        ),
    ]
