# Generated by Django 5.0.6 on 2024-09-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0012_hostel_gender_alter_room_bed"),
    ]

    operations = [
        migrations.AddField(
            model_name="hosteltype",
            name="semester_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="hosteltype",
            name="session_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
