# Generated by Django 5.0.6 on 2024-09-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0013_hosteltype_semester_rate_hosteltype_session_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="rate_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="rate_type",
            field=models.CharField(
                blank=True,
                choices=[("semester", "Semester"), ("session", "Session")],
                max_length=10,
                null=True,
            ),
        ),
    ]
