# Generated by Django 5.0.6 on 2024-09-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0014_booking_rate_price_booking_rate_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="school",
            field=models.CharField(
                blank=True,
                choices=[("nile", "Nile"), ("baze", "Baze")],
                max_length=20,
                null=True,
            ),
        ),
    ]
