# Generated by Django 5.0.6 on 2024-09-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0015_booking_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="hosteltype",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="hostel_gallery"),
        ),
    ]
