# Generated by Django 5.0.6 on 2024-10-12 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0017_hosteltypegallery"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hosteltype",
            old_name="price",
            new_name="baze_price",
        ),
    ]
