# Generated by Django 5.1 on 2024-10-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0018_rename_price_hosteltype_baze_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[("top", "Top"), ("fair", "Fair")],
                max_length=20,
                null=True,
            ),
        ),
    ]
