# Generated by Django 5.1 on 2024-10-15 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0020_alter_hostel_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hostelfeatures",
            name="hostel",
        ),
        migrations.AddField(
            model_name="hostelfeatures",
            name="hostel_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hostel.hosteltype",
            ),
        ),
    ]
