# Generated by Django 5.1 on 2024-10-16 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0021_remove_hostelfeatures_hostel_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Maintenance_request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "issue_category",
                    models.CharField(
                        choices=[
                            ("electrical issue", "Electrical Issue"),
                            ("plumbing", "Plumbing"),
                            ("appliances", "Appliances"),
                            ("lock/key issue", "Lock/Key Issue"),
                            ("others", "Others"),
                        ],
                        max_length=200,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "helpful",
                    models.ManyToManyField(
                        blank=True, related_name="helpful", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hostel.hostel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Maintenance Request",
                "ordering": ["-date"],
            },
        ),
    ]
