# Generated by Django 5.1 on 2024-10-16 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0022_maintenance_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenance_request",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hostel.booking",
            ),
        ),
        migrations.AddField(
            model_name="maintenance_request",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hostel.room",
            ),
        ),
    ]
