# Generated by Django 5.1 on 2024-10-19 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0023_maintenance_request_booking_maintenance_request_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenance_request",
            name="room",
        ),
    ]
