# Generated by Django 5.1 on 2024-10-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0025_remove_booking_student_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostel",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("mixed", "Mixed")],
                max_length=20,
                null=True,
            ),
        ),
    ]
