# Generated by Django 5.1 on 2024-11-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0028_block_hosteltype_block_room_block"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("mixed", "Mixed")],
                max_length=50,
                null=True,
            ),
        ),
    ]
