# Generated by Django 5.1 on 2024-11-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0029_block_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="fullname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
