# Generated by Django 5.1 on 2024-11-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0030_alter_booking_email_alter_booking_fullname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hosteltype",
            name="rate_type",
            field=models.CharField(
                blank=True,
                choices=[("semester", "Semester"), ("session", "Session")],
                max_length=10,
                null=True,
            ),
        ),
    ]
