# Generated by Django 5.1 on 2024-11-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0032_booking_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="avilable_bedspace",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
