# Generated by Django 5.1 on 2024-11-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0033_room_avilable_bedspace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="rate_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("semester", "Semester"),
                    ("session", "Session"),
                    ("flexible rate", "Flexible Rate"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
