# Generated by Django 5.1 on 2024-11-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0034_alter_booking_rate_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("review", models.TextField(blank=True, null=True)),
                ("reply", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "★☆☆☆☆"),
                            (2, "★★☆☆☆"),
                            (3, "★★★☆☆"),
                            (4, "★★★★☆"),
                            (5, "★★★★★"),
                        ],
                        default=None,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Reviews & Rating",
                "ordering": ["-date"],
            },
        ),
        migrations.AlterField(
            model_name="hostel",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    (1, "★☆☆☆☆"),
                    (2, "★★☆☆☆"),
                    (3, "★★★☆☆"),
                    (4, "★★★★☆"),
                    (5, "★★★★★"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
