# Generated by Django 5.1 on 2024-11-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0035_review_alter_hostel_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="flexible_plan_type",
            field=models.CharField(
                blank=True,
                choices=[("semester", "Semester"), ("session", "Session")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="initial_payment",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="remaining_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
