# Generated by Django 5.1 on 2024-11-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0036_booking_flexible_plan_type_booking_initial_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="remaining_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
