# Generated by Django 5.1 on 2024-11-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0037_alter_booking_remaining_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reminder_sent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
