# Generated by Django 5.1 on 2024-11-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0038_booking_reminder_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="rate_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("semester", "Semester"),
                    ("session", "Session"),
                    ("flexible plan", "Flexible Plan"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
