# Generated by Django 5.1 on 2024-11-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0040_alter_booking_remaining_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="remaining_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
