# Generated by Django 5.1 on 2024-11-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0041_alter_booking_remaining_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reminder_days",
            field=models.PositiveIntegerField(default=30),
        ),
    ]
