# Generated by Django 5.1 on 2024-11-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0042_booking_reminder_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderDays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Number of days before sending reminder emails",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="booking",
            name="reminder_days",
        ),
    ]
