# Generated by Django 5.1 on 2024-11-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0043_reminderdays_remove_booking_reminder_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="flexible_plan_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("semester", "Semester"),
                    ("session", "Session"),
                    ("flexible plan", "Flexible Plan"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
