# Generated by Django 5.1 on 2024-11-29 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostel", "0045_alter_block_hostel"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hostel.block",
            ),
        ),
    ]
